### ISSUE TITLE
Register using social auth

### ISSUE THREAD

**Issue by TimotheeJeannin** [pallets-eco/flask-security#751]
Hi,

It's great that social auth is supported but it would be awesome if users could register with social auth too.

I think most websites that support social auth also support it for registration. 

Tim

**Comment by ademaro** [comment]
@TimotheeJeannin, hi!

So you can implement it in your application any way you want. I don't think it should be part of the flask-security.

Here's a little example:
```python
@anonymous_user_required
@core.route("/auth/<name>")
def auth(name):
    client = oauth.create_client(name)
    if not client:
        abort(404)

    client.authorize_access_token()
    profile = client.userinfo()
    user = lookup_identity(profile["email"])  # Check if there is already such a user with this email
    if not user:
        user_datastore.create_user(email=profile["email"], is_active=True)  # Create (register) a new user
        user_datastore.commit()  # Updating the database with a new user
    login_user(user)
    user_datastore.commit()  # Updating the database for capturing the time of login
    return redirect(url_for("route_fn_for_user_dashboard"))
```

**Comment by chrisroat** [comment]
I think this is a great idea.

One important piece to consider is that the oauth dance returns an email, while the app may have a much more detailed User model with additional fields.  So there will be missing fields in the oauth registrations, which a form-based registration would capture.

I believe the addition of an update-user-info endpoint would mitigate this issue.  It would exist whenever the user model contains extra fields.  It would serve two uses:

- any logged in user can update the extra fields by going to the endpoint
- if oauth registration is enabled, the user would be redirected to the endpoint to finish registration (if there are extra fields to be filled in)

Does this sound reasonable?  Does it miss any cases?

**Comment by jwag956** [comment]
As @adermo demonstrates - it is fairly easy to do with existing APIs and I am not certain Flask-Security would offer much. To @TimotheeJeannin point - in my circle - I don't actually see social oauth as a replacement for registration - mostly used as an alternative method of authenticating.

Such a registration template would undoubtedly need to be custom and each social auth has different ways and fields that could be used to populate the user record- so that would be custom as well. And of course authorization is still the purview of Flask-Security - so that also would be custom code to translate social auth fields to FS roles etc.

If anyone has some specific ideas around what value FS could bring to this - lets open a new issue.
Thanks.
